### PR TITLE
RabbitMq fixes

### PR DESCRIPTION
**Pull request by grzonu**
without this you can't create workng services - DI problems with non-existent services

### CODE REVIEW

**Comment by mmucklo** [comment]
Hi @grzonu - I would have merged this, but the build was failing.

I made the changes myself in master.  Can you see if they work?

**Comment by grzonu** [comment]
i will check this when i will be at work (tommorow)

**Comment by grzonu** [comment]
It`s great thx

**Comment by mmucklo** [comment]
Good news, thx

**Pull request closed without merging**
