### PR TITLE
Symfony 7 support

### PR DESCRIPTION
**Pull request by emhovis**
Included in this are a few notable changes

- Migrated from Doctrine/annotations to native php attributes
- Removed dependency sensio/framework-extra-bundle (I couldn't find any usage anyhow)
- Added strong return types where necessary
- Changed supported versions of PHP to 8.1, Symfony to >=6

All of the annotation->attributes were performed with rector using Doctrine's changesets. I manually reviewed quite a bit where able but haven't had the luxury of testing everything.

### CODE REVIEW

**Review by mmucklo — APPROVED** [review]

**Comment by fliespl** [comment]
@mmucklo is it possible that new tag will be released someday?

**Comment by mmucklo** [comment]
Tags created.

**Comment by TomasVotruba** [comment]
Epic, thank you for blazing fast reaction :pray:

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
