### PR TITLE
#82 Added backwards compatible support for json encoded arguments

### PR DESCRIPTION
**Pull request by kralos**
Support non-string args via cli job enqueue.

Closes issue #82

### CODE REVIEW

**Comment by mmucklo** [comment]
I started a review of the changes.  The travis.yml simplification is fine, it was that way before and then there was some kind of problem I was encountering so it became an unruly mess like you saw.  Ideally it should probably be upgraded to sf4 at this point, but that's not you're responsibility :)

**Comment by mmucklo** [comment]
You should be able to see the rest of my comments inline...

**Comment by kralos** [comment]
nope... ?

**Comment by mmucklo** [comment]
Ok overall this is fairly solid, I made some comments which you apparently can’t see for some reason.  What I may do is just merge it and then patch things up a bit according to my comments.  It should leave the desired functionality intact, just some changes around the fringes.

I should be able to get to it within a day or two, Sunday/Monday at the latest, barring any emergencies.

**Pull request merged**
